-- 创建用户
CREATE USER zjy IDENTIFIED BY 1024  DEFAULT TABLESPACE USERS  TEMPORARY TABLESPACE TEMP;
-- 授权
GRANT DBA TO zjy WITH ADMIN OPTION;
GRANT CONNECT TO zjy WITH ADMIN OPTION;

-- 关闭用户连接(用户名大写)
SELECT username, sid, serial# FROM v$session WHERE username = 'LIBRA';
ALTER system kill SESSION '133,8028';

-- 删除用户
DROP USER LIBRA_PRODUCTION CASCADE;