-- 列名
SELECT LISTAGG('' || UPPER(A.COLUMN_NAME) || '', ', ') WITHIN GROUP(ORDER BY A.COLUMN_ID) AS columnNames
       -- wm_concat(LOWER(A.COLUMN_NAME)) as b
  FROM USER_TAB_COLS A
  JOIN USER_COL_COMMENTS B ON A.TABLE_NAME = B.TABLE_NAME AND A.COLUMN_NAME = B.COLUMN_NAME
 WHERE A.TABLE_NAME = UPPER('Tk_ShiTi')
 ORDER BY A.COLUMN_ID;

-- 查询包含字段的表
SELECT A.TABLE_NAME, B.Comments
  FROM USER_TAB_COLS A
  JOIN USER_TAB_COMMENTS B ON A.TABLE_NAME = B.TABLE_NAME
 WHERE UPPER(A.COLUMN_NAME) = UPPER('xuekeid');

-- 查询表信息
SELECT TABLE_NAME
  FROM USER_TABLES
 WHERE UPPER(TABLE_NAME) LIKE '%' || UPPER('ym_') || '%'
 ORDER BY TABLE_NAME;